export const monthObj = {
    "January": 31,
    "February": 28,
    "March": 31,
    "April": 30,
    "May": 31,
    "June": 30,
    "July": 31,
    "August": 31,
    "September": 30,
    "October": 31,
    "November": 30,
    "December": 31
};

export const monthArr = Object.keys(monthObj);

export const tbrDecks = {
    "Book Riot's Read Harder Challenge": {
        "description": 'This deck uses Book Riot\'s 2021 Read Harder Challenge prompts. https://bookriot.com/read-harder-2021/',
        "prompts": [
            'A book you’ve been intimidated to read',
            'A nonfiction book about anti-racism',
            'A non-European novel in translation',
            'An LGBTQ+ history book',
            'A genre novel by an Indigenous, First Nations, or Native American author',
            'A fanfic',
            'A fat-positive romance',
            'A romance by a trans or nonbinary author',
            'A middle grade mystery',
            'An SFF anthology edited by a person of color',
            'A food memoir by an author of color',
            'A work of investigative nonfiction by an author of color',
            'A book with a cover you don’t like',
            'A realistic YA book not set in the U.S., UK, or Canada',
            'A memoir by a Latinx author',
            'An own voices book about disability',
            'An own voices YA book with a Black main character that isn’t about Black pain',
            'A book by/about a non-Western world leader',
            'A historical fiction with a POC or LGBTQ+ protagonist',
            'A book of nature poems',
            'A children’s book that centers a disabled character but not their disability',
            'A book set in the Midwest',
            'A book that demystifies a common mental illness',
            'A book featuring a beloved pet where the pet doesn’t die'
        ]
    },
    "PopSugar Reading Challenge": {
        "description": 'This deck uses PopSugar\'s 2021 Reading Challenge prompts. Available here: https://www.popsugar.com/entertainment/reading-challenge-2021-47892177',
        "prompts": [
            'A book that\'s published in 2021',
            'An Afrofuturist book',
            'A book that has a heart, diamond, club, or spade on the cover',
            'A book by an author who shares your zodiac sign',
            'A dark academia book',
            'A book with a gem, mineral, or rock in the title',
            'A book where the main character works at your current or dream job',
            'A book that has won the Women\'s Prize For Fiction',
            'A book with a family tree',
            'A bestseller from the 1990s',
            'A book about forgetting',
            'A book you have seen on someone\'s bookshelf (in real life, on a Zoom call, in a TV show, etc.)',
            'A locked-room mystery',
            'A book set in a restaurant',
            'A book with a black-and-white cover',
            'A book by an Indigenous author',
            'A book that has the same title as a song',
            'A book about a subject you are passionate about',
            'A book that discusses body positivity',
            'A book found on a Black Lives Matter reading list',
            'A genre hybrid',
            'A book set mostly or entirely outdoors',
            'A book with something broken on the cover',
            'A book by a Muslim American author',
            'A book that was published anonymously',
            'A book with an oxymoron in the title',
            'A book about do-overs or fresh starts',
            'A magical realism book',
            'A book set in multiple countries',
            'A book set somewhere you\'d like to visit in 2021',
            'A book by a blogger, vlogger, YouTube video creator, or other online personality',
            'A book whose title starts with "Q," "X," or "Z"',
            'A book featuring three generations (grandparent, parent, child)',
            'A book about a social justice issue',
            'A book in a different format than what you normally read (audiobooks, ebooks, graphic novels)',
            'A book that has fewer than 1,000 reviews on Amazon or Goodreads',
            'A book you think your best friend would like',
            'A book about art or an artist',
            'A book everyone seems to have read but you',
            'The longest book (by pages) on your TBR list',
            'The shortest book (by pages) on your TBR list',
            'The book on your TBR list with the prettiest cover',
            'The book on your TBR list with the ugliest cover',
            'The book that\'s been on your TBR list for the longest amount of time',
            'A book from your TBR list you meant to read last year but didn\'t',
            'A book from your TBR list you associate with a favorite person, place, or thing',
            'A book from your TBR list chosen at random',
            'A DNF book from your TBR list',
            'A free book from your TBR list (gifted, borrowed, library)'
        ]
    },
    "Back to the Classics": {
        "description": 'A deck focused on reading the classics! We define this as any book written at least 50 years ago, but you can define it otherwise if you\'d like.',
        "prompts": [
            'A 19th century classic: any book first published from 1800 to 1899',
            'A 20th century classic: any book first published from 1900 to 1971. All books must have been published at least 50 years ago; the only exceptions are books which were written by 1971 and posthumously published.',
            'A classic by a woman author. Must have been written before 1971.',
            'A classic in translation, meaning any book first published in a language that is not your primary language. You may read it in translation or in its original language, if you prefer. Must have been written before 1971.',
            'A classic by BIPOC author; that is, a non-white author. Must have been written before 1971.',
            'A classic by a new-to-you author, i.e., an author whose work you have never read. Must have been written before 1971.',
            'New-to-you classic by a favorite author -- a new book by an author whose works you have already read. Must have been written before 1971.',
            'A classic about an animal, or with an animal in the title. The animal can be real or metaphorical. (i.e., To Kill a Mockingbird). Must have been written before 1971.',
            'A children\'s classic. Must have been written before 1971.',
            'A humorous or satirical classic. Must have been written before 1971.',
            'A travel or adventure classic (fiction or non-fiction). It can be a travelogue or a classic in which the main character travels or has an adventure. Must have been written before 1971.',
            'A classic play. Plays will only count in this category. Must have been written before 1971.'
        ]
    },
    "Reading Women Challenge": {
        "description": 'A deck focused on reading women and nonbinary authors comfortable being included in feminine-coded intitiatives.',
        "prompts": [
            'A Book Longlisted for the JCB Prize',
            'A Book written by an Author from Eastern Europe',
            'A Book About Women\'s Incarceration',
            'A Cookbook (or a book with a food-adjacdent topic) by a Woman of Color. ',
            'A Book with a Protagonist Older than 50',
            'A Book by a South American Author in Translation',
            'A Memoir by an Indigenous, First Nations, Native, or Aboriginal Woman',
            'A Book by a Neurodivergent Author',
            'A Crime Novel or Thriller in Translation',
            'A Book About the Natural World',
            'A Young Adult Novel by a Latinx Author',
            'A Poetry Collection by a Black Woman',
            'A Book with a Biracial Protagonist',
            'A Muslim Middle Grade Novel',
            'A Book Featuring a Queer Love Story',
            'A Book about a Woman in Politics',
            'A Book with a Rural Setting',
            'A Book with a Cover Designed by a Woman',
            'A Book by an Arab Author in Translation',
            'A Book by a Trans Author. This includes trans women and nonbinary trans authors comfortable being included in feminine-coded initiatives.',
            'A Fantasy Novel by an Asian Author',
            'A Nonfiction Book Focused on Social Justice',
            'A Short Story Collection by a Caribbean Author',
            'A Book by Alexis Wright',
            'A Book by Tsitsi Dangarembga',
            'A Book by Leila Aboulela',
            'A Book by Yoko Ogawa'
        ]
    },
    "Read the World": {
        "description": 'This deck prompts you to choose books based on setting. For example: "A book set in Europe", "A book set in Vietnam", "A book set in a country you want to visit", etc.',
        "prompts": [
            'A book set in Europe',
            'A book set in Asia',
            'A book set in South America',
            'A book set in North America',
            'A book set in Africa',
            'A book set in Australia',
            'A book set in Germany',
            'A book set in the UK',
            'A book set in France',
            'A book set in Italy',
            'A book set in Eastern Europe',
            'A book set in a country you have never been to',
            'A book set in a country you want to visit',
            'A book set in the Nordic Region',
            'A book set in the Middle East',
            'A book set in Nigeria',
            'A book set in West Africa',
            'A book set in Egypt',
            'A book set in South Africa',
            'A book set in India',
            'A book set in China',
            'A book set in Vietnam',
            'A book set in Japan',
            'A book set in New Zealand',
            'A book set in Russia',
            'A book set in Brazil',
            'A book set in Latin America',
            'A book set in Colombia',
            'A book set in Argentina',
            'A book set in Mexico',
            'A book set on an island',
            'A book set in the midwest (USA)',
            'A book set in the south (USA)',
            'A book set in New England (USA)',
            'A book set on the West Coast (USA)',
            'A book set on the East Coast (USA)',
            'A book set in Canada',
            'A book set in a country whose dominant language you don\'t speak',
            'A book set in a state (USA) you have never been to or have visited the least',
            'A book set in a state (USA) you love',
            'A book set in or near your hometown',
            'A book set at sea',
            'A book set in the desert',
            'A book set at the beach',
            'A book set in a cold climate',
            'A book set during a holiday you don\'t celebrate',
            'A book set in the woods',
            'A book set in the mountains'
        ]
    },
    "The ZORA Canon": {
        "description": 'This deck includes the titles curated for the ZORA Canon. These were chosen by the ZORA Editors as the 100 greatest books ever written by African American women. More info at: https://zora.medium.com/',
        "prompts": [
            'Our Nig by Harriet E. Wilson',
            'Incidents in the Life of a Slave Girl by Harriet Jacobs',
            'A Voice From the South: By a Black Woman of the South by Anna Julia Cooper',
            'Iola Leroy by Frances Harper',
            'The Red Record by Ida B. Wells',
            'There Is Confusion by Jessie Fauset',
            'Quicksand by Nella Larsen',
            'Passing by Nella Larsen',
            'Their Eyes Were Watching God by Zora Neale Hurston',
            'Tell My Horse: Voodoo and Life in Haiti and Jamaica by Zora Neale Hurston',
            'Moses, Man of the Mountain by Zora Neale Hurston',
            'The Street by Ann Petry',
            'Maud Martha by Gwendolyn Brooks',
            'Brown Girl, Brownstones by Paule Marshall',
            'A Raisin in the Sun by Lorraine Hansberry',
            'Selected Poems by Gwendolyn Brooks',
            'Funnyhouse of a Negro by Adrienne Kennedy',
            'Jubilee by Margaret Walker',
            'The Flagellants by Carlene Hatcher Polite',
            'The House of Dies Drear by Virginia Hamilton',
            'Coming of Age in Mississippi by Anne Moody',
            'I Know Why the Caged Bird Sings by Maya Angelou',
            'To Be Young, Gifted, and Black: Lorraine Hansberry in Her Own Words by Lorraine Hansberry',
            'The Black Woman: An Anthology by Toni Cade Bambara',
            'We a BaddDDD People by Sonia Sanchez',
            'The Third Life of Grange Copeland by Alice Walker',
            'Gorilla, My Love by Toni Cade Bambara',
            'Sula by Toni Morrison',
            'Oreo by Fran Ross',
            'Corregidora by Gayl Jones',
            'Eva’s Man by Gayl Jones',
            'For Colored Girls Who Have Considered Suicide When the Rainbow Is Enuf by Ntozake Shange',
            'Roll of Thunder, Hear My Cry by Mildred D. Taylor',
            'Meridian by Alice Walker',
            'Song of Solomon by Toni Morrison',
            'I’ve Been a Woman: New and Selected Poems by Sonia Sanchez',
            'Black Macho and the Myth of the Black Superwoman by Michele Wallace',
            'The Salt Eaters by Toni Cade Bambara',
            'The Heart of a Woman by Maya Angelou',
            'Women, Race, and Class by Angela Davis',
            'Ain’t I a Woman?: Black Women and Feminism by bell hooks',
            'All the Women Are White, All the Blacks Are Men, But Some of Us Are Brave, edited by Gloria T. Hull, Patricia Bell Scott, and Barbara Smith',
            'Zami: A New Spelling of My Name by Audre Lorde',
            'The Women of Brewster Place by Gloria Naylor',
            'Sassafrass, Cypress, and Indigo by Ntozake Shange',
            'The Color Purple by Alice Walker',
            'Fish Tales by Nettie Jones',
            'Homegirls: A Black Feminist Anthology, edited by Barbara Smith',
            'In Search of Our Mothers’ Gardens: Womanist Prose by Alice Walker',
            'When and Where I Enter: The Impact of Black Women on Race and Sex in America by Paula Giddings',
            'Sister Outsider by Audre Lorde',
            'Linden Hills by Gloria Naylor',
            'Radiance From the Waters: Ideals of Feminine Beauty in Mende Art by Sylvia Ardyn Boone',
            'Thomas and Beulah by Rita Dove',
            'Blacks by Gwendolyn Brooks',
            'Beloved by Toni Morrison',
            'Assata by Assata Shakur',
            'Black-Eyed Susans and Midnight Birds: Stories by and About Black Women, edited by Mary Helen Washington',
            'Invisibility Blues: From Pop to Theory by Michele Wallace',
            'Waiting to Exhale by Terry McMillan',
            'Parable of the Sower by Octavia E. Butler',
            'Ugly Ways by Tina McElroy Ansa',
            'The Black Christ by Kelly Brown Douglas',
            'The Selected Poems of Nikki Giovanni: 1968–1995 (A compilation of Nikki Giovanni’s poetry published in 1996)',
            'Killing the Black Body by Dorothy E. Roberts',
            'Parable of the Talents by Octavia E. Butler',
            'Black Picket Fences: Privilege and Peril Among the Black Middle Class by Mary Pattillo-McCoy',
            'Where We Stand: Class Matters by bell hooks',
            'Topdog/Underdog by Suzan-Lori Parks',
            'Ella Baker and the Black Freedom Movement: A Radical Democratic Vision by Barbara Ransby',
            'Fledgling by Octavia E. Butler',
            'Directed by Desire: The Collected Poems of June Jordan, edited by Jan Heller Levi and Sara Miles',
            'Native Guard by Natasha Trethewey',
            'African American Music: An Introduction by Mellonee V. Burnim and Portia K. Maultsby',
            'All Bound Up Together: The Woman Question in African American Public Culture, 1830–1900 by Martha S. Jones',
            'Blue-Chip Black by Karyn R. Lacy',
            'A Mercy by Toni Morrison',
            'Blood Dazzler by Patricia Smith',
            'The Warmth of Other Suns by Isabel Wilkerson',
            'The New Jim Crow by Michelle Alexander',
            'Salvage the Bones by Jesmyn Ward',
            'The Collected Poems of Lucille Clifton, edited by Kevin Young and Michael S. Glaser',
            'The Ethnic Project: Transforming Racial Fiction Into Ethnic Factions by Vilna Bashi Treitler',
            'Things I Should Have Told My Daughter: Lies, Lessons, and Love Affairs by Pearl Cleage',
            'Brown Girl Dreaming by Jacqueline Woodson',
            'Dark Matters: On the Surveillance of Blackness by Simone Browne',
            'The Fifth Season by N.K. Jemisin',
            'Pushout: The Criminalization of Black Girls in School by Monique W. Morris',
            'Sweat by Lynn Nottage',
            'Unequal City: Race, Schools, and Perceptions of Injustice by Carla Shedd',
            'White Rage: The Unspoken Truth of Our Racial Divide by Carol Anderson',
            'Whatever Happened to Interracial Love? by Kathleen Collins',
            'Freedom Is a Constant Struggle: Ferguson, Palestine, and the Foundations of a Movement by Angela Y. Davis, edited by Frank Barat',
            'Beyond Respectability: The Intellectual Thought of Race Women by Brittney C. Cooper',
            'How We Get Free: Black Feminism and the Combahee River Collective, edited by Keeanga-Yamahtta Taylor',
            'Sing, Unburied, Sing by Jesmyn Ward',
            'An American Marriage by Tayari Jones',
            'Race After Technology by Ruha Benjamin',
            'Wayward Lives, Beautiful Experiments by Saidiya Hartman',
            'Magical Negro by Morgan Parker'
        ]
    },
    "Booker Prize Winners": {
        "description": 'This deck includes all titles awarded the Booker Prize.',
        "prompts": [
            'Something to Answer For by P. H. Newby',
            'The Elected Member by Bernice Rubens',
            'Troubles by J. G. Farrell',
            'In a Free State by V. S. Naipaul',
            'G. by John Berger',
            'The Siege of Krishnapur by J. G. Farrell',
            'The Conservationist by Nadine Gordimer',
            'Holiday by Stanley Middleton',
            'Heat and Dust by Ruth Prawer Jhabvala',
            'Saville by David Storey',
            'Staying On by Paul Scott',
            'The Sea, the Sea by Iris Murdoch',
            'Offshore by Penelope Fitzgerald',
            'Rites of Passage by William Golding',
            'Midnight\'s Children by Salman Rushdie',
            'Schindler\'s Ark by Thomas Keneally',
            'Life & Times of Michael K by J. M. Coetzee',
            'Hotel du Lac by Anita Brookner',
            'The Bone People by Keri Hulme',
            'The Old Devils by Kingsley Amis ',
            'Moon Tiger by Penelope Lively',
            'Oscar and Lucinda by Peter Carey',
            'The Remains of the Day by Kazuo Ishiguro',
            'Possession by A. S. Byatt',
            'The Famished Road by Ben Okri',
            'The English Patient by Michael Ondaatje',
            'Sacred Hunger by Barry Unsworth',
            'Paddy Clarke Ha Ha Ha by Roddy Doyle',
            'How Late It Was, How Late by James Kelman',
            'The Ghost Road by Pat Barker',
            'Last Orders by Graham Swift',
            'The God of Small Things by Arundhati Roy',
            'Amsterdam by Ian McEwan',
            'Disgrace by J. M. Coetzee',
            'The Blind Assassin by Margaret Atwood',
            'True History of the Kelly Gang by Peter Carey',
            'Life of Pi by Yann Martel',
            'Vernon God Little by DBC Pierre',
            'The Line of Beauty by Alan Hollinghurst',
            'The Sea by John Banville',
            'The Inheritance of Loss by Kiran Desai',
            'The Gathering by Anne Enright',
            'The White Tiger by Aravind Adiga',
            'Wolf Hall by Hilary Mantel',
            'The Finkler Question by Howard Jacobson',
            'The Sense of an Ending by Julian Barnes',
            'Bring Up the Bodies by Hilary Mantel',
            'The Luminaries by Eleanor Catton',
            'The Narrow Road to the Deep North by Richard Flanagan',
            'A Brief History of Seven Killings by Marlon James',
            'The Sellout by Paul Beatty',
            'Lincoln in the Bardo by George Saunders',
            'Milkman by Anna Burns',
            'The Testaments by Margaret Atwood',
            'Girl, Woman, Other by Bernardine Evaristo',
            'Shuggie Bain by Douglas Stuart'
        ]
    },
    "Pulitzer Prize Winners for Fiction": {
        "description": 'This deck includes all titles awarded the Pulitzer Prize in Fiction.',
        "prompts": [
            '1918: His Family by Ernest Poole',
            '1919: The Magnificent Ambersons by Booth Tarkington',
            '1921: The Age of Innocence by Edith Wharton',
            '1922: Alice Adams by Booth Tarkington',
            '1923: One of Ours by Willa Cather',
            '1924: The Able McLaughlins by Margaret Wilson',
            '1925: So Big by Edna Ferber',
            '1926: Arrowsmith by Sinclair Lewis (declined prize)',
            '1927: Early Autumn by Louis Bromfield',
            '1928: The Bridge of San Luis Rey by Thornton Wilder',
            '1929: Scarlet Sister Mary by Julia Peterkin',
            '1930: Laughing Boy by Oliver La Farge',
            '1931: Years of Grace by Margaret Ayer Barnes',
            '1932: The Good Earth by Pearl S. Buck',
            '1933: The Store by Thomas Sigismund Stribling',
            '1934: Lamb in His Bosom by Caroline Miller',
            '1935: Now in November by Josephine Winslow Johnson',
            '1936: Honey in the Horn by Harold L. Davis',
            '1937: Gone with the Wind by Margaret Mitchell',
            '1938: The Late George Apley by John Phillips Marquand',
            '1939: The Yearling by Marjorie Kinnan Rawlings',
            '1940: The Grapes of Wrath by John Steinbeck',
            '1942: In This Our Life by Ellen Glasgow',
            '1943: Dragon\'s Teeth by Upton Sinclair',
            '1944: Journey in the Dark by Martin Flavin',
            '1945: A Bell for Adano by John Hersey',
            '1947: All the King\'s Men by Robert Penn Warren',
            '1948: Tales of the South Pacific by James A. Michener',
            '1949: Guard of Honor by James Gould Cozzens',
            '1950: The Way West by A. B. Guthrie, Jr.',
            '1951: The Town by Conrad Richter',
            '1952: The Caine Mutiny by Herman Wouk',
            '1953: The Old Man and the Sea by Ernest Hemingway',
            '1955: A Fable by William Faulkner',
            '1956: Andersonville by MacKinlay Kantor',
            '1958: A Death in the Family by James Agee (posthumous win)',
            '1959: The Travels of Jaimie McPheeters by Robert Lewis Taylor',
            '1960: Advise and Consent by Allen Drury',
            '1961: To Kill a Mockingbird by Harper Lee',
            '1962: The Edge of Sadness by Edwin O\'Connor',
            '1963: The Reivers by William Faulkner (posthumous win)',
            '1965: The Keepers of the House by Shirley Ann Grau',
            '1966: The Collected Stories of Katherine Anne Porter by Katherine Anne Porter',
            '1967: The Fixer by Bernard Malamud',
            '1968: The Confessions of Nat Turner by William Styron',
            '1969: House Made of Dawn by N. Scott Momaday',
            '1970: The Collected Stories of Jean Stafford by Jean Stafford',
            '1972: Angle of Repose by Wallace Stegner',
            '1973: The Optimist\'s Daughter by Eudora Welty',
            '1975: The Killer Angels by Michael Shaara',
            '1976: Humboldt\'s Gift by Saul Bellow',
            '1978: Elbow Room by James Alan McPherson',
            '1979: The Stories of John Cheever by John Cheever',
            '1980: The Executioner\'s Song by Norman Mailer',
            '1981: A Confederacy of Dunces by John Kennedy Toole (posthumous win)',
            '1982: Rabbit Is Rich by John Updike',
            '1983: The Color Purple by Alice Walker',
            '1984: Ironweed by William Kennedy',
            '1985: Foreign Affairs by Alison Lurie',
            '1986: Lonesome Dove by Larry McMurtry',
            '1987: A Summons to Memphis by Peter Taylor',
            '1988: Beloved by Toni Morrison',
            '1989: Breathing Lessons by Anne Tyler',
            '1990: The Mambo Kings Play Songs of Love by Oscar Hijuelos',
            '1991: Rabbit at Rest by John Updike',
            '1992: A Thousand Acres by Jane Smiley',
            '1993: A Good Scent from a Strange Mountain by Robert Olen Butler',
            '1994: The Shipping News by E. Annie Proulx',
            '1995: The Stone Diaries by Carol Shields',
            '1996: Independence Day by Richard Ford',
            '1997: Martin Dressler: The Tale of an American Dreamer by Steven Millhauser',
            '1998: American Pastoral by Philip Roth',
            '1999: The Hours by Michael Cunningham',
            '2000: Interpreter of Maladies by Jhumpa Lahiri',
            '2001: The Amazing Adventures of Kavalier & Clay by Michael Chabon',
            '2002: Empire Falls by Richard Russo',
            '2003: Middlesex by Jeffrey Eugenides',
            '2004: The Known World by Edward P. Jones',
            '2005: Gilead by Marilynne Robinson',
            '2006: March by Geraldine Brooks',
            '2007: The Road by Cormac McCarthy',
            '2008: The Brief Wondrous Life of Oscar Wao by Junot Díaz',
            '2009: Olive Kitteridge by Elizabeth Strout',
            '2010: Tinkers by Paul Harding',
            '2011: A Visit From the Goon Squad by Jennifer Egan',
            '2012: No award given - choose a book published in 2012!',
            '2013: The Orphan Master\'s Son by Adam Johnson',
            '2014: The Goldfinch by Donna Tartt',
            '2015: All the Light We Cannot See by Anthony Doerr',
            '2016: The Sympathizer by Viet Thanh Nguyen',
            '2017: The Underground Railroad by Colson Whitehead',
            '2018: Less by Andrew Sean Greer',
            '2019: The Overstory by Richard Powers',
            '2020: The Nickel Boys by Colson Whitehead'
        ]
    },
    "Genre Roulette": {
        "description": 'This deck prompts you to read books based on genre or type. For example: "A fantasy novel", "The first book in a series","A non-fiction book", etc',
        "prompts": [

        ]
    },
    "Prompt mixer!": {
        "description": 'This option will mix all prompts together. Does not include the ZORA Canon titles or Booker and Pulitzer prize winners.',
        "prompts": [

        ]
    },
    "Surprise me!": {
        "description": 'This option will randomly choose one of the decks for you.',
        "prompts": [

        ]
    }
};